import React,{useEffect,useId,useRef,useState} from 'react';
import {CARDS,TYPE_NAMES,STAGES,GLOSSARY} from './cards.js';
import {createDuel,startBattle,playCard,endTurn,chooseCard,previewCard,readDuel,saveDuel} from './engine.js';
import './duel.css';
import {cue} from './audio.js';
import batterSheet from '../../assets/duel/batter.png';
import pitcherSheet from '../../assets/duel/pitcher.png';

const iconPaths={bat:'M8 26L25 7L29 7L29 11L11 28Z',shield:'M7 6H25V20L16 29L7 20Z',eye:'M3 14L10 8H22L29 14V18L22 24H10L3 18ZM13 12V20H19V12Z',book:'M4 7H14L16 9L18 7H28V25H18L16 27L14 25H4Z',ball:'M10 5H22L27 10V22L22 27H10L5 22V10ZM10 10V22H12V10ZM20 10V22H22V10Z',comet:'M3 5L19 11L25 11L29 15V23L23 29H15L11 25L9 17ZM15 17V23H23V17Z',double:'M4 9H12V17H4ZM20 17H28V25H20ZM12 17H20V19H12Z',diamond:'M16 3L29 16L16 29L3 16ZM16 9L9 16L16 23L23 16Z',target:'M5 5H27V27H5ZM9 9V23H23V9ZM13 13H19V19H13Z',spark:'M18 2L6 19H14L12 30L27 12H18Z',moon:'M15 3H21L17 7V17L23 23H29L25 28H13L5 20V10L10 5Z',sun:'M13 2H19V7H13ZM13 25H19V30H13ZM2 13H7V19H2ZM25 13H30V19H25ZM10 10H22V22H10Z'};
function PixelIcon({art}){return <svg viewBox="0 0 32 32" aria-hidden="true" shapeRendering="crispEdges"><path fill="currentColor" fillRule="evenodd" d={iconPaths[art]}/></svg>;}
function Card({kind,onClick,selected,problem,preview,label}){const c=CARDS[kind];return <button className={`duel-card ${c.type} ${selected?'selected':''} ${problem?'unavailable':''}`} onClick={onClick} aria-label={label||c.name} aria-pressed={!!selected}>
  <span className="card-cost">{c.cost}</span><span className="card-type">{TYPE_NAMES[c.type]}</span><div className="card-art"><PixelIcon art={c.art}/></div><strong>{c.name}</strong><span className="card-rule">{c.text}</span><span className="card-foot">{preview&&!preview.problem?`피해 ${preview.damage} · 방어 +${preview.block}`:c.flavor}</span></button>;}
function Sprite({who,frame=0}){
  const clip=useId(),pitcher=who==='pitcher',height=pitcher?724:793;
  // Generated poses are NOT evenly spaced. Explicit atlas bounds prevent adjacent limbs leaking into a frame.
  const [x,width,offset]=(pitcher?[[0,600,70],[740,500,-600],[1280,892,-1300]]:[[0,660,70],[680,730,-550],[1420,563,-1250]])[frame];
  return <svg aria-hidden="true" className="duel-sprite" viewBox={`0 0 ${height} ${height}`} style={{overflow:'visible'}}><defs><clipPath id={clip}><rect x={x} y="0" width={width} height={height}/></clipPath></defs><g transform={`translate(${offset} 0)`}><image clipPath={`url(#${clip})`} href={pitcher?pitcherSheet:batterSheet} width={pitcher?2172:1983} height={height}/></g></svg>;
}
function Bar({value,max,label,block=0}){return <div className="duel-vital"><div><b>{label}</b><span>{block>0&&`방어 ${block} · `}{value}/{max}</span></div><div className="vital-track"><i style={{width:`${100*value/max}%`}}/></div></div>;}
export default function Duel(){
  const [initial]=useState(()=>{try{return {save:readDuel(localStorage)}}catch{return {error:'저장을 읽지 못했습니다. 새 런을 시작할 수 있습니다.'}}});
  const [s,setS]=useState(initial.save),[screen,setScreen]=useState('menu'),[modal,setModal]=useState(null),[selected,setSelected]=useState(null),[fx,setFx]=useState(null),[frame,setFrame]=useState(0),[error,setError]=useState(initial.error||'');
  const [sound,setSound]=useState(false);
  const current=useRef(s),lock=useRef(false),timers=useRef([]);
  useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);
  useEffect(()=>{const close=e=>{if(e.key==='Escape')setModal(null)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
  function persist(next){current.current=next;setS(next);try{saveDuel(localStorage,next);setError('')}catch{setError('저장 공간에 접근할 수 없습니다. 이 창을 닫으면 진행을 잃을 수 있습니다.')}}
  function act(fn,animated=false){if(lock.current)return;const next=fn(current.current);if(next===current.current)return;persist(next);setSelected(null);if(animated){lock.current=true;if(sound)cue(next.last.kind);setFx(next.last);setFrame(1);const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;timers.current.forEach(clearTimeout);timers.current=[setTimeout(()=>setFrame(2),reduced?10:180),setTimeout(()=>{setFx(null);setFrame(0);lock.current=false;timers.current=[]},reduced?60:620)];}}
  function fresh(){persist(createDuel());setScreen('run');setModal(null);setSelected(null)}
  const b=s?.battle,showBattle=screen==='run'&&b&&(s.phase==='battle'||fx),byId=id=>s.deck.find(c=>c.id===id),choice=selected&&b?.hand.includes(selected)?previewCard(s,selected):null;
  const pile=modal&&['draw','discard','exhaust','deck'].includes(modal)?(modal==='deck'?s.deck:b[modal].map(byId)):null;
  return <div className="duel-app">
    <header className="duel-header"><button className="wordmark" onClick={()=>{if(!lock.current)setScreen('menu')}}>9ZONE<span> DUGOUT</span></button><span className="edition">DECKBUILDING / ACT 0</span><nav><button onClick={()=>{if(!sound)cue('skill');setSound(!sound)}} aria-label={`소리 ${sound?'켜짐':'꺼짐'}`}>♪ {sound?'ON':'OFF'}</button>{s&&<button onClick={()=>setModal('deck')}>덱 {s.deck.length}</button>}<button onClick={()=>setModal('help')}>플레이 방법</button></nav></header>
    {error&&<div className="save-error" role="alert">{error}<button onClick={()=>s&&persist(s)}>저장 재시도</button></div>}
    {screen==='menu'?<main className="duel-title stadium"><div className="title-copy"><span className="eyebrow">A BASEBALL CARD ROGUELIKE</span><h1>공을 맞히지 마.<br/><em>승부를 설계해.</em></h1><p>상대의 의도는 공개되어 있다.<br/>어떤 카드로 바꿀지는, 네 선택이다.</p><div className="title-actions"><button className="primary" onClick={()=>s&&!['won','lost'].includes(s.phase)?setModal('new'):fresh()}>새 런 시작</button>{s&&<button onClick={()=>setScreen('run')}>이어하기</button>}</div><small>투수 1명 · 카드 12종 · 전투 4회 · 카드 보상 3회<br/>완성 게임이 아닌, 카드 연계의 재미를 검증하는 ACT 0</small></div><div className="title-actor"><Sprite who="batter"/></div><div className="title-caption">THE FIRST INNING<br/><b>해 질 녘, 마지막 연습 경기.</b></div></main>
    :showBattle?<main className="duel-combat">
      <div className="battle-ribbon"><span>0{s.stage+1} / 04 — {STAGES[s.stage].name}</span><b>TURN {b.turn}</b><span>카드 선택 → 한 번 더 클릭해 사용</span></div>
      <section className={`duel-arena stadium ${fx?.kind==='hit'?'impact':''}`} aria-label="전투 구장">
        <div className="fighter player"><div className="fighter-name">YOU <span>타자 · 한결</span></div><Bar value={s.hp} max={s.maxHp} label="평정심" block={b.block}/></div>
        <div className="fighter opponent"><div className="fighter-name">THE ROOKIE <span>투수 · 태성</span></div><Bar value={b.enemyHp} max={STAGES[s.stage].hp} label="제구" block={b.enemyBlock}/></div>
        <div className={`intent ${b.intent.kind}`} title={b.intent.detail}><span>NEXT INTENT · 확정 행동</span><strong>{b.intent.name}</strong><b>{b.intent.attack?`공격 ${b.intent.attack}`:`방어 ${b.intent.block} · 공격력 +2`}</b></div>
        <div className={`actor-left ${fx?.kind==='pitch'?'receiving':''}`}><Sprite who="batter" frame={fx?.kind==='hit'?frame:0}/></div><div className="actor-right"><Sprite who="pitcher" frame={fx?.kind==='pitch'?frame:0}/></div>
        {fx&&<div key={s.stats.cards+'-'+s.stats.turns} className={`duel-fx ${fx.kind}`}><span className="pixel-ball"/><strong>{fx.kind==='hit'?`−${fx.damage}`:fx.kind==='pitch'?(fx.damage?`−${fx.damage}`:'BLOCK'):CARDS[fx.card]?.name}</strong></div>}
        <div className="battle-caption" role="status">{s.last?.text}<span>{b.intent.detail}</span></div>
      </section>
      <section className="duel-table">
        <div className="table-toolbar"><div className="energy"><b>{b.energy}</b><span>행동력</span></div><div className="buffs"><span title={GLOSSARY[3][1]}>노림 <b>{b.aim}</b></span><span title={GLOSSARY[4][1]}>유리한 카운트 <b>{b.count}</b></span>{b.calm>0&&<span>침착함 <b>{b.calm}</b></span>}<small>이번 턴 {b.played}장 · 기술 {b.skills}장</small></div><button className="end-turn" disabled={!!fx} onClick={()=>act(endTurn,true)}>턴 종료 <span>예상 피해 {Math.max(0,b.intent.attack-b.block)}</span></button></div>
        <div className="duel-hand">{b.hand.map(id=><Card key={id} kind={byId(id).kind} selected={selected===id} preview={previewCard(s,id)} problem={previewCard(s,id).problem} onClick={()=>{if(!lock.current){if(selected===id)act(x=>playCard(x,id),true);else setSelected(id)}}}/>)}{!b.hand.length&&<p className="empty-hand">손패를 모두 사용했습니다. 턴을 종료해 5장을 뽑으세요.</p>}</div>
        <div className="table-footer"><div className="pile-buttons"><button onClick={()=>setModal('draw')}>뽑을 카드 {b.draw.length}</button><button onClick={()=>setModal('discard')}>버린 카드 {b.discard.length}</button><button onClick={()=>setModal('exhaust')}>소멸 {b.exhaust.length}</button></div><div className="card-confirm">{selected&&choice?<><span>{choice.problem||`${CARDS[byId(selected).kind].name} · 사용 후 행동력 ${choice.energy}`}</span><button className="primary" disabled={!!choice.problem||!!fx} onClick={()=>act(x=>playCard(x,selected),true)}>카드 사용</button></>:<span>공격은 확정 적중. 방어와 카드 순서를 설계하세요.</span>}</div></div>
      </section>
    </main>:s.phase==='map'?<main className="duel-map stadium"><div className="map-copy"><span className="eyebrow">THE FIRST INNING</span><h1>네 번의 승부.<br/>하나의 덱.</h1><p>매 승리마다 평정심 5 회복.<br/>세 번의 보상으로 나만의 연계를 만드세요.</p><Bar value={s.hp} max={s.maxHp} label="평정심"/></div><div className="map-route">{STAGES.map((stage,i)=><div key={i} className={`route-node ${i===s.stage?'current':''} ${i<s.stage?'cleared':''}`}><span>{i<s.stage?'✓':`0${i+1}`}</span><div><h2>{stage.name}</h2><p>{stage.sub}</p></div>{i===s.stage?<button className="primary" onClick={()=>act(startBattle)}>승부 시작</button>:<small>{i<s.stage?'돌파':'대기'}</small>}</div>)}</div></main>
    :s.phase==='reward'?<main className="reward-screen"><span className="eyebrow">VICTORY / REWARD {s.stage+1} OF 3</span><h1>다음 승부를 바꿀 한 장.</h1><p>평정심 5 회복 완료 · {s.hp}/{s.maxHp} — 선택한 카드는 다음 전투부터 덱에 들어갑니다.</p><div className="reward-cards">{s&&[...(s.stage===0?['lure','rally','calm']:s.stage===1?['flow','scout','bunt']:['finisher','slug','watch'])].map(kind=><Card key={kind} kind={kind} selected={selected===kind} onClick={()=>setSelected(kind)}/>)}</div><div className="reward-actions"><button className="primary" disabled={!selected} onClick={()=>act(x=>chooseCard(x,selected))}>선택한 카드 획득</button><button onClick={()=>act(x=>chooseCard(x,'skip'))}>건너뛰기 · 평정심 +4</button></div></main>
    :<main className="duel-result stadium"><span className="eyebrow">{s.phase==='won'?'THE FIRST INNING — CLEAR':'RUN ENDED'}</span><h1>{s.phase==='won'?'이 승부는 네가 만들었다.':'아직, 끝난 건 아니다.'}</h1><p>{s.victories}/4 승리 · 사용 카드 {s.stats.cards}장 · 막아낸 피해 {s.stats.blocked}</p><p>다음 런에서는 카드의 순서와 보상을 바꿔 보세요.</p><button className="primary" onClick={fresh}>다시 도전</button><button onClick={()=>setModal('deck')}>완성한 덱 보기</button></main>}
    {modal&&<div className="duel-backdrop" onClick={()=>setModal(null)}><section className="duel-modal" role="dialog" aria-modal="true" aria-label={modal==='help'?'플레이 방법':'카드 정보'} onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setModal(null)} aria-label="닫기">×</button>{modal==='new'?<><h2>진행 중인 런을 새로 시작할까요?</h2><p>이 검증판의 현재 저장만 교체합니다. 이전 버전 저장은 유지됩니다.</p><button className="primary" onClick={fresh}>새 런으로 교체</button></>:modal==='help'?<><span className="eyebrow">READ → BUILD → RESOLVE</span><h2>코스를 찍는 게임이 아닙니다.</h2><p>투수의 다음 행동은 공개된 그대로 실행됩니다. 행동력 3으로 여러 카드를 사용한 뒤 턴을 끝내세요. 선택한 카드를 한 번 더 클릭하거나 ‘카드 사용’을 누릅니다.</p><div className="combo-example">볼 골라내기 → 유리한 카운트 획득<br/>직구 유도 → 상대 의도를 직구로 변경<br/>풀스윙 → 확정 추가 피해</div><p>첫 승리 보상에서 직구 유도를 고르면 이 연계를 만들 수 있습니다. 뽑을 카드 목록은 순서를 숨깁니다. 손패는 턴마다 버리고 5장을 새로 뽑습니다.</p>{GLOSSARY.map(([term,text])=><p key={term}><b>{term}</b> — {text}</p>)}<h3>카드 도감 · 12종</h3><div className="collection">{Object.keys(CARDS).map(kind=><Card key={kind} kind={kind}/>)}</div></>:pile?<><h2>{{deck:'현재 덱',draw:'뽑을 카드 · 순서 비공개',discard:'버린 카드',exhaust:'이번 전투에서 소멸한 카드'}[modal]}</h2><div className="collection">{[...pile].sort((a,b)=>a.kind.localeCompare(b.kind)).map(c=><Card key={c.id} kind={c.kind}/>)}</div>{!pile.length&&<p>비어 있습니다.</p>}</>:null}</section></div>}
  </div>;
}
