import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {describe,expect,it} from 'vitest';
import {createV10Duel,enterV10Node} from '../src/duel/engine.js';
import {validateV10State,V10_SAVE_KEY} from '../src/duel/v10-storage.js';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const meta=JSON.parse(readFileSync(path.join(ROOT,'docs/design/v12/baseline.json'),'utf8'));

describe('V12 P0-1 baseline contract',()=>{
  it('pins the exact pre-P0 branch head as the Before SHA',()=>{
    expect(meta.slice).toBe('P0-1');
    expect(meta.branch).toBe('claude/feedback-review-plan-vw24at');
    expect(meta.baselineSha).toBe('a1cbf625fa558bb463999fee47998868d155fcb4');
    /* The V12 branch was never merged, so that commit is not in main's history and `git cat-file` failed
       in every main checkout. The record is kept (sha + branch above); its reachability is not a
       contract main can keep. */
    expect(meta.baselineSha).toMatch(/^[0-9a-f]{40}$/);
  });

  it('commits the representative combat save generated by the real engine',()=>{
    expect(()=>execFileSync('git',['ls-files','--error-unmatch',meta.fixture],{cwd:ROOT,stdio:'pipe'})).not.toThrow();
    const actual=JSON.parse(readFileSync(path.join(ROOT,meta.fixture),'utf8'));
    const expected=enterV10Node(createV10Duel(meta.seed),meta.entryNodeId);
    expect(validateV10State(actual)).toBe(true);
    // This historical Before fixture predates the visual pitcher roster.
    // Compare all game state after excluding only opponent display identity.
    const gameplayState=state=>{
      const copy=structuredClone(state);
      for(const node of copy.runMap.nodes){
        if(!node.opponent)continue;
        delete node.opponent.name;
        delete node.opponent.artId;
        delete node.preview;
        // V13 Act 1 tuning (lower HP, fewer balls) postdates this fixture: balance numbers are excluded,
        // structure (map, deck, hand, pending pitch) still has to match.
        delete node.opponent.maxHp;
        delete node.opponent.escalation;
      }
      delete copy.pitcher.hp;delete copy.pitcher.maxHp;
      delete copy.battle.intent;
      delete copy.v10.opponent;
      return copy;
    };
    expect(gameplayState(actual)).toEqual(gameplayState(expected));
    expect(actual.version).toBe(10);
    expect(actual.phase).toBe('battle');
    expect(actual.v10.nodeId).toBe(meta.entryNodeId);
    expect(meta.saveKey).toBe(V10_SAVE_KEY);
  });

  it('pins the required collector and three review viewports',()=>{
    expect(meta.collector).toBe('scripts/v12-baseline.mjs');
    expect(meta.viewports).toEqual([
      {name:'mobile-390x844',width:390,height:844},
      {name:'mobile-landscape-844x390',width:844,height:390},
      {name:'desktop-1440x900',width:1440,height:900},
    ]);
    const collector=readFileSync(path.join(ROOT,meta.collector),'utf8');
    expect(collector).toContain('createV10Duel');
    expect(collector).toContain('enterV10Node');
    expect(collector).toContain('MAIN RUN 이어하기');
  });
  it('commits the canonical three-viewport Before shot set at exact viewport dimensions',()=>{
    const shots=[
      ['p0-1-390x844.png',390,844],
      ['p0-1-844x390.png',844,390],
      ['p0-1-1440x900.png',1440,900],
    ];
    for(const [name,width,height] of shots){
      const relative=path.join('docs/design/v12/shots',name);
      expect(()=>execFileSync('git',['ls-files','--error-unmatch',relative],{cwd:ROOT,stdio:'pipe'})).not.toThrow();
      const png=readFileSync(path.join(ROOT,relative));
      expect(png.subarray(0,8).toString('hex')).toBe('89504e470d0a1a0a');
      expect(png.readUInt32BE(16)).toBe(width);
      expect(png.readUInt32BE(20)).toBe(height);
      expect(png.length).toBeGreaterThan(10000);
    }
  });

});
