import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {describe,expect,it} from 'vitest';
import {createV10Duel,enterV10Node} from '../src/duel/engine.js';
import {validateV10State,V10_SAVE_KEY} from '../src/duel/v10-storage.js';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const meta=JSON.parse(readFileSync(path.join(ROOT,'docs/design/v12/baseline.json'),'utf8'));

describe('V12 P0-1 baseline contract',()=>{
  it('pins the exact pre-P0 branch head as the Before SHA',()=>{
    expect(meta.slice).toBe('P0-1');
    expect(meta.branch).toBe('claude/feedback-review-plan-vw24at');
    expect(meta.baselineSha).toBe('a1cbf625fa558bb463999fee47998868d155fcb4');
    expect(()=>execFileSync('git',['cat-file','-e',meta.baselineSha+'^{commit}'],{cwd:ROOT,stdio:'pipe'})).not.toThrow();
  });

  it('commits the representative combat save generated by the real engine',()=>{
    expect(()=>execFileSync('git',['ls-files','--error-unmatch',meta.fixture],{cwd:ROOT,stdio:'pipe'})).not.toThrow();
    const actual=JSON.parse(readFileSync(path.join(ROOT,meta.fixture),'utf8'));
    const expected=enterV10Node(createV10Duel(meta.seed),meta.entryNodeId);
    expect(validateV10State(actual)).toBe(true);
    expect(actual).toEqual(expected);
    expect(actual.version).toBe(10);
    expect(actual.phase).toBe('battle');
    expect(actual.v10.nodeId).toBe(meta.entryNodeId);
    expect(meta.saveKey).toBe(V10_SAVE_KEY);
  });

  it('pins the required collector and three review viewports',()=>{
    expect(meta.collector).toBe('scripts/v12-baseline.mjs');
    expect(meta.viewports).toEqual([
      {name:'mobile-390x844',width:390,height:844},
      {name:'mobile-landscape-844x390',width:844,height:390},
      {name:'desktop-1440x900',width:1440,height:900},
    ]);
    const collector=readFileSync(path.join(ROOT,meta.collector),'utf8');
    expect(collector).toContain('createV10Duel');
    expect(collector).toContain('enterV10Node');
    expect(collector).toContain('MAIN RUN 이어하기');
  });
});
